improved path discovery for patchtool

diff --git a/distsrc/linux/patchtool b/distsrc/linux/patchtool
--- a/distsrc/linux/patchtool
+++ b/distsrc/linux/patchtool
@@ -11,34 +11,36 @@ VERBOSE=false
 APPID="1374840"
 GAME_DIR=""
 ACTION=""
-SCRIPTS_DIR="scripts"
 OVERRIDE=false
 
-if [ ! -d "$SCRIPTS_DIR" ]; then
-    echo "Error: \"$SCRIPTS_DIR\" directory not found."
-    exit 1
-fi
+# Get the directory where the script is located
+BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 
-HASH_FILE="$SCRIPTS_DIR/hashes.csv"
-if [[ ! -f "$HASH_FILE" ]]; then
-    echo "Error: \"$HASH_FILE\" not found." >&2
-    exit 1
-fi
-
-# Read hashes from CSV
-prePatchHash=$(awk -F'"' '$2=="prePatch" {print $4}' "$HASH_FILE")
-postPatchHash=$(awk -F'"' '$2=="postPatch" {print $4}' "$HASH_FILE")
-
-if [[ -z "$prePatchHash" || -z "$postPatchHash" ]]; then
-    echo "Error: Failed to read hashes from $HASH_FILE."
-    exit 1
-fi
+SCRIPTS_DIR="$BASE_DIR/scripts"
 
 # Default install locations for Steam
 STEAM_ROOTS=(
     "$HOME/.local/share/Steam"
     "$HOME/.steam/steam"
 )
+
+load_hashes() {
+	if [ ! -d "$SCRIPTS_DIR" ]; then
+    	echo "Error: \"$SCRIPTS_DIR\" directory not found."
+    	exit 1
+	fi
+	
+	local hash_file="$SCRIPTS_DIR/hashes.csv"
+	if [[ ! -f "$hash_file" ]]; then
+		prePatchHash=""
+		postPatchHash=""
+    	echo "Hash file not present.  Version validation will be skipped." >&2
+	else
+		# Read hashes from CSV
+		prePatchHash=$(awk -F'"' '$2=="prePatch" {print $4}' "$hash_file")
+		postPatchHash=$(awk -F'"' '$2=="postPatch" {print $4}' "$hash_file")
+	fi
+}
 
 # Display usage instructions
 usage() {
@@ -49,14 +51,14 @@ This patch should support SteamOS, Ubuntu, and most other x86-based
 Linux distributions.  The patch is for Dark Deity version 1.5.8.
 
 Usage: 
-    ./${SCRIPT_NAME} COMMAND [FLAGS] [directory]
+  ./${SCRIPT_NAME} COMMAND [FLAGS] [directory]
 COMMAND can be one of
-    -h, -?, --help    Show this help	
-    -i, --install     Install the patch
-    -u, --uninstall   Uninstall the patch
-    -c, --hash        Calculate the hash of data.win and data.win.old if it exists
+  -h, -?, --help  Show this help	
+  -i, --install   Install the patch
+  -u, --uninstall Uninstall the patch
+  -c, --hash      Calculate the hash of data.win and data.win.old if it exists
 FLAGS can be one or more of
-	-o, --override    Ignore pre-patch validation failures and patch anyway
+  -o, --override    Ignore pre-patch validation failures and patch anyway
 	
 [directory] optionally specifies the directory of the Dark Deity executable 
 
@@ -129,13 +131,13 @@ do_uninstall() {
 do_install() {
     echo "--- Building patched.win ---"
     rm -f "$GAME_DIR/patched.win"
-    utmt_cli/UndertaleModCli load "$GAME_DIR/data.win" -s "scripts/nongmlmods.csx" -s "tools/scriptupdater.csx" -o "${GAME_DIR}/patched.win"
+    $BASE_DIR/utmt_cli/UndertaleModCli load "$GAME_DIR/data.win" -s "$BASE_DIR/scripts/nongmlmods.csx" -s "$BASE_DIR/tools/scriptupdater.csx" -o "${GAME_DIR}/patched.win"
     echo "--- Renaming data.win to data.win.old to save as a backup ---"
     rm -f "$GAME_DIR/data.win.old"
     mv "$GAME_DIR/data.win" "$GAME_DIR/data.win.old"
     echo "--- Renaming patched.win to data.win ---"
     mv "$GAME_DIR/patched.win" "$GAME_DIR/data.win"	
-    cp "tools/removepatch.sh" "$GAME_DIR/removepatch.sh"              
+    cp "$BASE_DIR/tools/removepatch.sh" "$GAME_DIR/removepatch.sh"              
 }
 
 do_version() {
@@ -179,12 +181,19 @@ EOF
 }
 
 validate_prehash() {
+	# If there's no hash to check against, then validation always succeeds
+    if [[ -z "$prePatchHash" ]]; then
+    	return 0
+    fi
+    
+    # If data.win already matches the post hash then the patch is already installed
     local currentHash=$(get_sha256_hash "$GAME_DIR/data.win")
     if [[ "$currentHash" = "$postPatchHash" ]]; then
         echo "Patch was already installed.  Nothing to do."
         exit 0
     fi
 	
+	# If the data.win matches the pre-hash then we're ready to patch
     if [[ "$currentHash" = "$prePatchHash" ]]; then
         return 0
     fi
@@ -196,8 +205,8 @@ validate_prehash() {
     fi
 
     if [[ "$backupHash" = "$prePatchHash" ]]; then
-        # if data.old.win is the right pre-version, then run do_uninstall to delete and replace it
-        # with data.old.win before starting the patch process
+        # if data.old.win is the right version, then run do_uninstall to restore data.win 
+        # from it before starting the patch process
         do_uninstall
         return 0
     fi
@@ -207,7 +216,7 @@ validate_prehash() {
     	return 0
    	fi
         	
-    # Neither data.win nor data.win.old is the right version and the user didn't want to override, so the patch can't be applied
+    # Neither data.win nor data.win.old is the right version and the user doesn't want to override, so the patch can't be applied.  Give some info and signal failure.
     echo "Expected pre-patch hash:  $prePatchHash"
     echo "Expected post-patch hash: $postPatchHash"
     echo "data.win hash:            $currentHash"
@@ -220,11 +229,13 @@ validate_prehash() {
 }
 
 validate_posthash() {
-	if [[ $OVERRIDE = true ]]; then
+	# If there's no hash or it is being overridden, then validation always succeeds
+    if [[ -z "$postPatchHash" || $OVERRIDE = true ]]; then
 		echo -e "\033[32mThe patch installation was successful.\033[0m"
-		exit 0
-	fi	
+    	return 0
+    fi
 		
+	# Report whether the final hash matches the expected then end the script.
 	local currentHash=$(get_sha256_hash "$GAME_DIR/data.win")
 	if [[ "$currentHash" = "$postPatchHash" ]]; then
 		echo "Post-patch hash validation passed."
@@ -254,6 +265,7 @@ set_action() {
 main() {
     case "$ACTION" in
         "install")
+        	load_hashes
             validate_gamedir
             validate_prehash
             do_install
